spring.application.name=oauth
server.port=9190
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

oauth.admin.username=admin
oauth.admin.password=123456

oauth.client.id=gateway-app
oauth.client.secret={noop}12345
oauth.client.redirect-uri=http://127.0.0.1:8080/login/oauth2/code/client-app
oauth.client.redirect-uri-auth=http://127.0.0.1:8080/authorized
oauth.client.post-logout-redirect-uri=http://127.0.0.1:8080/logout

oauth.flutter.client.id=flutter-app
oauth.flutter.client.redirect-uri=com.ngonzano.app://oauth/callback

oauth.internal-token=${OAUTH_INTERNAL_TOKEN:1234567890}

oauth.issuer=http://127.0.0.1:9190
